version: '3.9'

services:
  flask:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ipc: host
    restart: always

    ports:
      - 30000:30000
    volumes:
      - type: volume
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true

