version: '3.9'

services:
  flask:
    privileged: true
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ipc: host
    restart: always

    ports:
      - 30000:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro


