version: '3.9'

services:
  flask:
    privileged: true
    network_mode: host
    build:
      context: ./
      dockerfile: Dockerfile-cpu

    ipc: host
    restart: always

    ports:
      - 8098:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro


