version: '3.9'

services:
  flask:
    privileged: true
    pid: host
    build:
      context: ./
      dockerfile: Dockerfile-cpu

    ipc: host
    restart: always

    ports:
      - 8098:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/hosts:/etc/hosts:ro
      - /:/host:ro,rslave


